version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis_service
    restart: always
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes", "--replicaof", "no", "one"]
    volumes:
      - redis_data:/data

  mongodb_old:
    image: mongo:3.4.21
    container_name: mongodb_old_service
    restart: always
    ports:
      - "27018:27017"  # Используем 27018, чтобы не конфликтовать с новой версией
    volumes:
      - mongo_old_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: old_admin
      MONGO_INITDB_ROOT_PASSWORD: old_secret

  mongodb_new:
    image: mongo:latest
    container_name: mongodb_new_service
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_new_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret

volumes:
  redis_data:
  mongo_old_data:
  mongo_new_data:
